### ISSUE TITLE
Major Exception in System Checklist Script

### ISSUE THREAD

**Issue by technotherion** [2Shirt/WizardKit#10]
![image](https://user-images.githubusercontent.com/13829537/35072300-d85bed60-fb98-11e7-827d-0af5ebc5e64e.png)

**Comment by technotherion** [comment]
`2018-01-17 1451-0800: HH-Toolbox: System Checklist Tool
2018-01-17 1459-0800: Starting System Checklist for Ticket #----
2018-01-17 1459-0800: Configure
2018-01-17 1459-0800:         Explorer...                     Done
2018-01-17 1459-0800:         Updating Clock...               NS
2018-01-17 1459-0800: Cleanup
2018-01-17 1459-0800:         Desktop...                      Done
2018-01-17 1459-0800:         AdwCleaner...                   Done
2018-01-17 1459-0800: Backup System Information
2018-01-17 1459-0800:         AIDA64 reports...               Done
2018-01-17 1502-0800:         File listing...                 Done
2018-01-17 1503-0800:         Power plans...                  Done
2018-01-17 1503-0800:         Product Keys...                 Done
2018-01-17 1503-0800:         Registry...                     Done
2018-01-17 1503-0800: User Data
2018-01-17 1504-0800:     User: HomeGroupUser$
2018-01-17 1504-0800: Major exception
2018-01-17 1504-0800: Please let 2Shirt know by opening an issue on GitHub
2018-01-17 1504-0800: Traceback (most recent call last):
2018-01-17 1504-0800:   File "C:\HH\Tools\.bin\Scripts\system_checklist.py", line 64, in <module>
2018-01-17 1504-0800:     show_user_data_summary()
2018-01-17 1504-0800:   File "C:\HH\Tools\.bin\Scripts\functions\info.py", line 463, in show_user_data_summary
2018-01-17 1504-0800:     size =      folders[folder]['Size'],
2018-01-17 1504-0800: KeyError: 'Size'`

**Comment by technotherion** [comment]
2018-01-17 1451-0800: HH-Toolbox: System Checklist Tool
2018-01-17 1459-0800: Starting System Checklist for Ticket #----
2018-01-17 1459-0800: Configure
2018-01-17 1459-0800:         Explorer...                     Done
2018-01-17 1459-0800:         Updating Clock...               NS
2018-01-17 1459-0800: Cleanup
2018-01-17 1459-0800:         Desktop...                      Done
2018-01-17 1459-0800:         AdwCleaner...                   Done
2018-01-17 1459-0800: Backup System Information
2018-01-17 1459-0800:         AIDA64 reports...               Done
2018-01-17 1502-0800:         File listing...                 Done
2018-01-17 1503-0800:         Power plans...                  Done
2018-01-17 1503-0800:         Product Keys...                 Done
2018-01-17 1503-0800:         Registry...                     Done
2018-01-17 1503-0800: User Data
2018-01-17 1504-0800:     User: HomeGroupUser$
2018-01-17 1504-0800: Major exception
2018-01-17 1504-0800: Please let 2Shirt know by opening an issue on GitHub
2018-01-17 1504-0800: Traceback (most recent call last):
2018-01-17 1504-0800:   File "C:\HH\Tools\.bin\Scripts\system_checklist.py", line 64, in <module>
2018-01-17 1504-0800:     show_user_data_summary()
2018-01-17 1504-0800:   File "C:\HH\Tools\.bin\Scripts\functions\info.py", line 463, in show_user_data_summary
2018-01-17 1504-0800:     size =      folders[folder]['Size'],
2018-01-17 1504-0800: KeyError: 'Size'

**Comment by 2Shirt** [comment]
@technotherion If it's not too much trouble, would you replace the `.bin/Scripts/functions/info.py` file from the one in the f7f3f0d commit and try to reproduce the error?

**Comment by technotherion** [comment]
Edits made to kit #1; will test when I get a system that needs checklisting. Thanks!

**Comment by technotherion** [comment]
Checklist script tested on 2 separate systems. The commit you made fixed it.
