### ISSUE TITLE
System Checklist error

### ISSUE THREAD

**Issue by technotherion** [2Shirt/WizardKit#4]
When running systemchecklist.cmd, the following error occurs:
```
Major exception
  Please let 2Shirt know and they'll look into it (include the details below).
Traceback (most recent call last):
  File "D:\HH-Toolbox\.bin\Scripts\system_checklist.py", line 97, in <module>
    run_xmplay()
  File "D:\HH-Toolbox\.bin\Scripts\functions\diags.py", line 69, in run_xmplay
    popen_program(cmd)
  File "D:\HH-Toolbox\.bin\Scripts\functions\common.py", line 302, in popen_program
    popen_obj = subprocess.Popen(cmd, shell=shell, startupinfo=startupinfo)
  File "subprocess.py", line 709, in __init__
  File "subprocess.py", line 997, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

Press Enter to exit...
```

**Comment by 2Shirt** [comment]
Going to attempt to reproduce the issue.

**Comment by 2Shirt** [comment]
Unable to reproduce error.
