### ISSUE TITLE
Mac fans not set to max during Prime95

### ISSUE THREAD

**Issue by 2Shirt** [2Shirt/WizardKit#88]
> One was a mid 2010 mbp. The other was a 2015 retina, I believe.

**Comment by 2Shirt** [comment]
HW-Diags crashed when trying to run apple-fans on a MacBook8,1

    2019-01-26 1414-0800: Selected Tests:
    2019-01-26 1414-0800:   Prime95         ^[[32mEnabled^[[0m
    2019-01-26 1414-0800:   NVMe / SMART    ^[[32mEnabled^[[0m
    2019-01-26 1414-0800:   badblocks       ^[[32mEnabled^[[0m
    2019-01-26 1414-0800:   I/O Benchmark   ^[[32mEnabled^[[0m
    2019-01-26 1414-0800:
    2019-01-26 1414-0800: Starting Prime95 test
    2019-01-26 1414-0800: Getting idle temps...           Done
    2019-01-26 1414-0800: Starting Prime95
    2019-01-26 1414-0800: Major exception
    2019-01-26 1414-0800: Please let support know by opening an issue on Github
    2019-01-26 1414-0800: Traceback (most recent call last):
    2019-01-26 1414-0800:   File "/usr/local/bin/hw-diags-menu", line 18, in <module>
    2019-01-26 1414-0800:     menu_diags(state, sys.argv)
    2019-01-26 1414-0800:   File "/usr/local/bin/functions/hw_diags.py", line 908, in menu_diags
    2019-01-26 1414-0800:     run_hw_tests(state)
    2019-01-26 1414-0800:   File "/usr/local/bin/functions/hw_diags.py", line 1080, in run_hw_tests
    2019-01-26 1414-0800:     f(state, test_obj)
    2019-01-26 1414-0800:   File "/usr/local/bin/functions/hw_diags.py", line 1360, in run_mprime_test
    2019-01-26 1414-0800:     run_program(['apple-fans', 'max'])
    2019-01-26 1414-0800:   File "/usr/local/bin/functions/common.py", line 510, in run_program
    2019-01-26 1414-0800:     return subprocess.run(**cmd_kwargs)
    2019-01-26 1414-0800:   File "/usr/lib/python3.7/subprocess.py", line 487, in run
    2019-01-26 1414-0800:     output=stdout, stderr=stderr)
    2019-01-26 1414-0800: subprocess.CalledProcessError: Command '['apple-fans', 'max']' returned non-zero exit status 1.
    2019-01-26 1415-0800: Upload crash details to Nextcloud? [Y/N]: Yes

    #############################
    Runtime Details:

    sys.argv: ['/usr/local/bin/hw-diags-menu', '--cli']

    global_vars: {
      BinDir:           /usr/local/bin
      Date:             2019-01-26
      Date-Time:        2019-01-26_1354_-0800
      LogDir:           /home/tech/Logs/None_2019-01-26_1414_-0800
      LogFile:          /home/tech/Logs/None_2019-01-26_1414_-0800/Hardware Diagnostics.log
      TmpDir:           /tmp/tmp.rcKGKIKWjF
      Tools: {
        SevenZip:       7z
        wimlib-imagex:  wimlib-imagex   
      }
      Env: 
        DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
        HOME:           /home/tech
        LANG:           en_US.UTF-8
        LC_CTYPE:       en_US.UTF-8
        LESS:           -R
        LOGNAME:        tech
        LSCOLORS:       Gxfxcxdxbxegedabagacad
        LS_COLORS:      rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=40;33;01:ow=40;33:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
        MAIL:           /var/spool/mail/tech
        MOZ_PLUGIN_PATH: /usr/lib/mozilla/plugins
        OLDPWD:         /home/tech
        PAGER:          less
        PATH:           /usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
        PWD:            /home/tech
        SHELL:          /bin/zsh
        SHLVL:          2
        TERM:           screen
        TMUX:           /tmp/tmux-1000/default,1037,0
        TMUX_PANE:      %0
        USER:           tech
        XDG_RUNTIME_DIR: /run/user/1000
        XDG_SEAT:       seat0
        XDG_SESSION_CLASS: user
        XDG_SESSION_ID: 1
        XDG_SESSION_TYPE: tty
        XDG_VTNR:       1
        ZSH:            /home/tech/.oh-my-zsh
        ZSH_TMUX_TERM:  screen
        _:              /usr/bin/tmux
        _ZSH_TMUX_FIXED_CONFIG: /home/tech/.oh-my-zsh/plugins/tmux/tmux.extra.conf
    }

**Comment by 2Shirt** [comment]
Since CPU thermal limits have been implemented I'm going to silence this error.
